---
- name: kubeadm join
  become: true
  become_user: root
  shell: |
         if ! [ -d /var/tmp/kubeadm-join ]; then
             kubeadm reset -f && kubeadm join --token "{{ kubeadm_token }}" --discovery-token-unsafe-skip-ca-verification "{{ hostvars[groups.kubeadm_master[0]].lan_ip }}:6443" && mkdir /var/tmp/kubeadm-join
         fi
